language: java

jdk:
  - openjdk14

sudo: false

env:

  global:

  CODECOV_TOKEN="3b28a22f-1c7d-4de1-a146-66c2220d0fc8"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - Mishail.avram@mail.ru
    on_success: never # default: change
    on_failure: always # default: always